apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-auditpolicy
  namespace: kube-system
  annotations:
    policy.mcm.ibm.com/standards: FISMA, HIPAA
    policy.mcm.ibm.com/categories: SystemAndCommunicationsProtections
    policy.mcm.ibm.com/controls: MutationAdvisor
spec:
  complianceType: musthave
  remediationAction: inform
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  policy-templates:
    - objectDefinition:
        apiVersion: audit.policies.ibm.com/v1alpha1
        kind: AuditPolicy # Verify if audit is enabled
        metadata:
          name: policy-auditpolicy-example
          label: 
            category: "System-Integrity"
        spec:
          severity: low
          namespaceSelector:
            include: ["default","kube-*"]
            exclude: ["kube-system"]
          clusterAuditPolicy:
            auditPolicyRules:
              "kubernetes": ignore
              "auth-idp": ignore
              "platform-api": ignore
              "helmapi": ignore
              "platform-identity-manager": ignore
              "platform-identity-provider": ignore
              "vulnerability-advisor": ignore
          remediationAction: inform # enforce or inform
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-auditpolicy
  namespace: kube-system
placementRef:
  name: placement-policy-auditpolicy
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
subjects:
- name: policy-auditpolicy
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: placement-policy-auditpolicy
  namespace: kube-system
spec:
  clusterLabels:
    matchExpressions:
    - key: cloud
      operator: In
      values:
      - IBM
