apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-vulnerabilitypolicy-1
  namespace: kube-system
  annotations:
    policy.mcm.ibm.com/standards: NIST
    policy.mcm.ibm.com/categories: SystemAndCommunicationsProtections
    policy.mcm.ibm.com/controls: VulnerbilityAdvisor
spec:
  complianceType: musthave
  remediationAction: inform
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  policy-templates:
    - objectDefinition:
        apiVersion: policies.ibm.com/v1alpha1
        kind: VulnerabilityPolicy # detect image vulnerabilities
        metadata:
          name: policy-vulnerabilitypolicy-1-example
          label:
            category: "System-Integrity"
        spec:
          namespaceSelector:
            include: ["default","kube-*"]
            exclude: ["kube-system"]
          remediationAction: inform # enforce or inform
          severity: medium
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-vulnerabilitypolicy-1
  namespace: kube-system
placementRef:
  name: placement-policy-vulnerabilitypolicy-1
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
subjects:
- name: policy-vulnerabilitypolicy-1
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: placement-policy-vulnerabilitypolicy-1
  namespace: kube-system
spec:
  clusterLabels:
    matchExpressions:
    - key: cloud
      operator: In
      values:
      - VMware
